# Generated by Django 5.1.7 on 2025-04-08 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzasAPI', '0002_remove_cash_price_transaction_dia_semana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], max_length=20, null=True)),
                ('amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzasAPI.account')),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzasAPI.category')),
            ],
        ),
    ]
