# Generated by Django 5.1.7 on 2025-04-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzasAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='dia_semana',
            field=models.IntegerField(default=0, help_text='Día de semana (0-6 donde 0 es lunes)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hora_dia',
            field=models.IntegerField(default=0, help_text='Hora del día (0-23)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mes',
            field=models.IntegerField(default=1, help_text='Mes (1-12)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='concept',
            field=models.CharField(default='Ingreso', max_length=255),
        ),
    ]
