# Generated by Django 5.1.6 on 2025-03-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzasAPI', '0002_alter_cash_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number_account',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
