# Generated by Django 5.1.6 on 2025-03-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzasAPI', '0003_alter_account_number_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='symbol',
        ),
    ]
